name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: Release Linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        name: build-for-linux-64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
      - uses: wangyoucao577/go-release-action@v1
        name: build-for-windows-64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
